name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: {}
jobs:
  Lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: wistia/parse-tool-versions@32f568a4ffd4bfa7720ebf93f171597d1ebc979a # v2.1.1
        with:
          postfix: _TOOL_VERSION
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ${{ env.UV_TOOL_VERSION }}
          activate-environment: true
          enable-cache: true
      - name: Linting
        run: |
          uv run pre-commit run --all-files
  Tests:
    needs: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: wistia/parse-tool-versions@32f568a4ffd4bfa7720ebf93f171597d1ebc979a # v2.1.1
        with:
          postfix: _TOOL_VERSION
      - uses: extractions/setup-crate@7577c1bdf2d95e6d65d532788f35ed79d4b1dda2 # v2.0.1
        with:
          repo: casey/just
          version: ${{ env.JUST_TOOL_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ${{ env.UV_TOOL_VERSION }}
          activate-environment: true
          enable-cache: true
      - name: Install Python
        run: uv python install ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: uv sync
      - name: Pytest run
        run: just test -v
